### PR TITLE
Create a Moderation Team

### PR DESCRIPTION
**Pull request by lehnberg**
[Link to rendered document](https://github.com/mimblewimble/grin-rfcs/blob/562abbf8f7282e3716e422b3466a12ca7262c0b6/text/0000-moderation-team.md)

After several discussions with community participants I'm creating a draft RFC to open up the discussions about moderation and how we would like this to be handled. Still early and incomplete, feedback is already welcomed however and ideas of how the team should work.

An **RFC shepherd** (preferably one that is also not a member of the core team) is needed. If you're up for the task, make yourself known! ✊

### CODE REVIEW

**Comment by j01tz** [comment]
Willing to shepherd this if no one else steps up :+1:

**Comment by grn1** [comment]
I would like to suggest public mod logs:

Moderation actions such as kicks, bans and content removals should be automatically logged for traceability.

Ideally publicly for transparency like for example for the tezos subreddit:
https://moddit.ffff00.news/r/tezos

Generally moderators should try to be transparent about their actions, like for example with proactive moderation reports or on (reasonable) public request.

**Comment by lehnberg** [comment]
@j01tz - thanks - assigning you as shepherd!

@grn1 having public mod logs is a great idea, not sure whether we can keep such a log automated on keybase, but some kind of log should be really straight forward to keep, even if it's done manually. Does it make sense to add this to the RFC, or is it something that the moderation team themselves would work out and manage at their discretion once a team has been established?

**Comment by grn1** [comment]
@lehnberg the mod team probably needs to figure out how to maintain a log, but a general standard to keep up transparency about mod actions where possible may be good to mention in the RFC. I think this is fundamentally important for crypto communities, because there are so many colliding interests in crypto and transparency can protect honest parties from dishonest parties.

**Comment by jaspervdm** [comment]
> Online community moderation

Should we be explicit which platforms/channels are considered to be in scope for this team? i.e. grin forum, mimblewimble org repo's on github (?), grin/* gitter, grincoin team on keybase

**Comment by lehnberg** [comment]
@jaspervdm the moderation team cannot have remit over any community that it's not appointed moderator to by the community admins, if that makes sense.

The thinking so far has been to be open and welcoming for any community that wishes to join up and take advantage of the team, the one criteria said so far is that they would need to adhere to the Grin code of conduct.

So even if the initial scope might be the list you mention, if there are Grin telegram communities that want to join up for example, they should/would be welcomed.

**Comment by j01tz** [comment]
Adding this checklist to help track some more things to be included:

- [ ] Bootstrapping: who will be the starting team members?
- [ ] Example: what is an example of the moderation team in action?
- [ ] Alternatives: are there any other moderation alternatives like self-moderation or core-moderation that are better?
- [ ] Prior art: are there other moderation methods used by other similar communities that haven't been considered?

**Comment by lehnberg** [comment]
As discussed in the [last governance meeting](https://github.com/mimblewimble/grin-pm/blob/master/notes/20200505-meeting-governance.md#49-create-moderation-team), I'm closing this due to lack of community interest and activity. If and when we see renewed interest, this can be re-opened or a new RFC can be proposed in its place.

**Pull request closed without merging**
