### PR TITLE
WIP: e2e encrypted slates over http(s)

### PR DESCRIPTION
**Pull request by DavidBurkett**
This RFC is incomplete, and has several placeholders throughout. The technical details of the proposal will be finished if there is a general consensus around the usefulness and viability of the approach.

### CODE REVIEW

**Comment by i1skn** [comment]
I have a double sided opinion in this topic. From one perspective it would definitely improve the situation, when a centralised relay service went rogue. Also, other wallets could start to use these services because of the trust issue would be no longer an issue. From another perspective I feel we should be going into direction of i2p or Grinbox'ish approaches, when we would not have a centralised service.

So, as an improvement of the current situation is a great idea, but I feel like our long term goal should be in slightly different direction. WDYT?

**Comment by DavidBurkett** [comment]
Yes, I largely agree with you, but this is something I've had in mind for about a year now, and never bothered because I've been waiting for a long-term solution. But here we are a year later with very little progress made toward the long term goal.

This is something we could implement quickly, without causing too much disruption.

**Comment by i1skn** [comment]
Well, then I'm supporting this idea, until `we could implement quickly` holds.

**Comment by xiaojay** [comment]
it is quite like grinbox solution, except without offline receive function.
so if we want to  standardize it  and make exchange/pool to support it, why not we  standardize grinbox solution?
just my two cents .

**Comment by DavidBurkett** [comment]
Slatepack will be implemented shortly, so no need for this.

**Pull request closed without merging**
